services:
  db:
    container_name: leaQ_db
    image: mariadb:11.5.2-noble
    restart: always
    environment:
      TZ: Asia/Tokyo
    env_file:
      - backend/.env
    ports:
      - "3306:3306"
    healthcheck:
      test: mariadb-admin ping -h 127.0.0.1 -u root -p$$MARIADB_ROOT_PASSWORD
      interval: 1s
      timeout: 10s
      retries: 60

  minio:
    container_name: leaQ_minio
    image: minio/minio:RELEASE.2024-08-17T01-24-54Z
    env_file:
      - backend/.env
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server --console-address ":9001" /data

  mc: # MinIO Client
    container_name: leaQ_mc
    image: minio/mc:RELEASE.2024-08-17T11-33-50Z
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      until (mc alias set bucket http://minio:9000 minioadmin minioadmin);
      do sleep 1;
      done;
      mc mb bucket/leaq;
      exit 0;
      "
