version: '3'

tasks:
  build:
    cmds:
      - go build -o backend/myapp backend/main.go
    desc: "Build the Go application"
  
  test:
    cmds:
      - go test backend/...
    desc: "Run all tests"
  
  up:
    desc: "Bring up Docker containers"
    cmds:
      - docker compose up -d

  down:
    desc: "Stop Docker containers"
    cmds:
      - docker compose down

  run:
    deps: [build]
    cmds:
      - ./backend/myapp
    desc: "Run the Go application"

  lint:
    cmds:
      - golangci-lint run
    desc: "Run the linter"

  logs:
    desc: "View Docker container logs"
    cmds:
      - docker compose logs -f

  db: 
    desc: "Access MySQL container"
    cmds:
      - docker compose exec db bash
